- name: Git setup user.email
  git_config:
    name: user.email
    scope: global
    value: dominick.brasileiro1@gmail.com
  tags:
    - git

- name: Git setup user.name
  git_config:
    name: user.name
    scope: global
    value: Dominick Brasileiro
  tags:
    - git

- name: Git setup user.signingkey
  git_config:
    name: user.signingkey
    scope: global
    value: "{{ pgp_key_id }}"
  tags:
    - git

- name: Git setup commit.gpgsign
  git_config:
    name: commit.gpgsign
    scope: global
    value: true
  tags:
    - git

- name: Git setup tag.gpgSign
  git_config:
    name: tag.gpgSign
    scope: global
    value: true
  tags:
    - git

- name: Git setup pull.rebase
  git_config:
    name: pull.rebase
    scope: global
    value: "true"
  tags:
    - git

- name: Git setup init.defaultBranch
  git_config:
    name: init.defaultBranch
    scope: global
    value: master
  tags:
    - git

- name: Git setup push.autoSetupRemote
  git_config:
    name: push.autoSetupRemote
    scope: global
    value: "true"
  tags:
    - git

- name: Git setup core.editor
  git_config:
    name: core.editor
    scope: global
    value: nvim
  tags:
    - git

- name: Git setup alias.c
  git_config:
    name: alias.c
    scope: global
    value: commit
  tags:
    - git

- name: Git setup alias.s
  git_config:
    name: alias.s
    scope: global
    value: status
  tags:
    - git

- name: Git setup alias.b
  git_config:
    name: alias.b
    scope: global
    value: branch
  tags:
    - git

- name: Git setup alias.co
  git_config:
    name: alias.co
    scope: global
    value: checkout
  tags:
    - git
