- name: Installing git
  homebrew:
    name: git
    state: present
    update_homebrew: yes
  tags:
    - install
    - git

- name: Git config user.email
  git_config:
    scope: global
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: 'user.email', value: 'dominick.brasileiro1@gmail.com' }
    - { key: 'user.name', value: 'Dominick Brasileiro' }
    - { key: 'user.signingkey', value: '{{ pgp_key_id }}' }
    - { key: 'commit.gpgsign', value: 'true' }
    - { key: 'tag.gpgSign', value: 'true' }
    - { key: 'pull.rebase', value: 'true' }
    - { key: 'init.defaultBranch', value: 'master' }
    - { key: 'push.autoSetupRemote', value: 'true' }
    - { key: 'core.editor', value: 'nvim' }
    - { key: 'alias.c', value: 'commit' }
    - { key: 'alias.s', value: 'status' }
    - { key: 'alias.b', value: 'branch' }
    - { key: 'alias.co', value: 'checkout' }
  tags:
    - git

