- name: Decrypt PGP private key
  copy:
    src: keys/pgp/secret.asc
    dest: /tmp/secret.asc
    mode: 0600

- name: Import PGP private key
  ansible.builtin.command:
    cmd: "gpg --import /tmp/secret.asc"
  become_user: "dominickbrasileiro"

- name: Remove the decrypted file
  ansible.builtin.file:
    path: /tmp/secret.asc
    state: absent
