- name: Decrypt PGP key
  ansible.builtin.command:
    cmd: "ansible-vault decrypt --output=/tmp/secret.asc keys/pgp/secret.asc"
  args:
    creates: /tmp/secret.asc
  changed_when: false

- name: Import PGP private key
  ansible.builtin.command:
    cmd: "gpg --import /tmp/secret.asc"
  become_user: "dominickbrasileiro"

- name: Remove the decrypted file
  ansible.builtin.file:
    path: /tmp/secret.asc
    state: absent
