- name: Decrypt secrets.env
  ansible.builtin.command:
    cmd: ansible-vault decrypt --output=/tmp/.zsecret secrets.env
  args:
    creates: /tmp/.zsecret
  changed_when: false

- name: Move decrypted file to ~/.zsecret
  ansible.builtin.command:
    cmd: mv /tmp/.zsecret ~/.zsecret
  args:
    creates: ~/.zsecret

- name: Set correct permissions for .zsecret
  ansible.builtin.file:
    path: ~/.zsecret
    owner: "{{ ansible_env.USER }}"
    mode: '0600'

- name: Ensure .zsecret is sourced in .zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'source ~/.zsecret'
    create: yes
