- name: Install .zsecret file
  copy:
    src: secrets.env
    dest: ~/.zsecret
    mode: 0600

- name: Ensure .zsecret is sourced in .zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'source ~/.zsecret'
    create: yes
