- name: Configuring sudoers.d/yabai
  become: true
  shell: 'echo "dominickbrasileiro ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | tee /private/etc/sudoers.d/yabai'

- name: Stoping yabai service
  ignore_errors: true
  shell: yabai --stop-service

- name: Uninstalling yabai service
  ignore_errors: true
  shell: yabai --uninstall-service

- name: Installing yabai service
  shell: yabai --start-service

